//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acta_reunion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acta_reunion()
        {
            this.Detalle_participacion = new HashSet<Detalle_participacion>();
        }
    
        public string id_reunion { get; set; }
        public string id_proyecto { get; set; }
        public string rol { get; set; }
        public string id_etapa { get; set; }
        public string detalle_minuta { get; set; }
        public Nullable<System.DateTime> fecha_reunion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_participacion> Detalle_participacion { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Etapa Etapa { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
