//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public decimal id_descto { get; set; }
        public Nullable<double> porc_descto { get; set; }
        public Nullable<decimal> id_seguro_sald { get; set; }
        public Nullable<decimal> id_AFP { get; set; }
        public string Persona_run { get; set; }
        public Nullable<decimal> id_trabajador { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual Trabajador_empresa Trabajador_empresa { get; set; }
        public virtual Seguro_salud Seguro_salud { get; set; }
    }
}
