//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class descuento
    {
        public decimal id_descto { get; set; }
        public Nullable<decimal> porc_descto { get; set; }
        public string id_AFP { get; set; }
        public string id_seguro_sald { get; set; }
        public string Trabajador_empresa_run { get; set; }
        public Nullable<decimal> Trabajador_empresa_id_trabajador { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual Trabajador_empresa Trabajador_empresa { get; set; }
        public virtual seguro_salud seguro_salud { get; set; }
    }
}
