//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_boleta
    {
        public decimal id_detalle_boleta { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string id_boleta { get; set; }
        public string id_producto { get; set; }
    
        public virtual Boleta Boleta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
