//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_participacion
    {
        public decimal id_detalle_participacion { get; set; }
        public string id_reunion { get; set; }
        public string run { get; set; }
    
        public virtual Acta_reunion Acta_reunion { get; set; }
        public virtual participante participante { get; set; }
    }
}
