//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_participacion
    {
        public decimal id_detalle_participacion { get; set; }
        public string id_reunion { get; set; }
        public string run { get; set; }
    
        public virtual Acta_reunion Acta_reunion { get; set; }
        public virtual Participante Participante { get; set; }
    }
}
