//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion_tecnica
    {
        public string id_inspeccion_tec { get; set; }
        public string id_tarea { get; set; }
        public string detalle_inspeccion_t { get; set; }
        public Nullable<decimal> nivel_avance { get; set; }
    
        public virtual Tarea Tarea { get; set; }
    }
}
