//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vialisEntities : DbContext
    {
        public vialisEntities()
            : base("name=vialisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acta_reunion> Acta_reunion { get; set; }
        public virtual DbSet<AFP> AFPs { get; set; }
        public virtual DbSet<Asistencia> Asistencias { get; set; }
        public virtual DbSet<boleta> boletas { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<ciudad> ciudads { get; set; }
        public virtual DbSet<comuna> comunas { get; set; }
        public virtual DbSet<Contrato> Contratoes { get; set; }
        public virtual DbSet<Cotizacion> Cotizacions { get; set; }
        public virtual DbSet<descuento> descuentoes { get; set; }
        public virtual DbSet<detalle_boleta> detalle_boleta { get; set; }
        public virtual DbSet<detalle_cotizacion> detalle_cotizacion { get; set; }
        public virtual DbSet<detalle_participacion> detalle_participacion { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Etapa> Etapas { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Hito> Hitoes { get; set; }
        public virtual DbSet<Inspeccion_tecnica> Inspeccion_tecnica { get; set; }
        public virtual DbSet<Pago> Pagoes { get; set; }
        public virtual DbSet<participante> participantes { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Proyecto> Proyectoes { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<registro_avance> registro_avance { get; set; }
        public virtual DbSet<seguro_salud> seguro_salud { get; set; }
        public virtual DbSet<Stock_RRFF_EMPRESA> Stock_RRFF_EMPRESA { get; set; }
        public virtual DbSet<stock_RRFF_PROYECTO> stock_RRFF_PROYECTO { get; set; }
        public virtual DbSet<subcategoria> subcategorias { get; set; }
        public virtual DbSet<Sueldo> Sueldoes { get; set; }
        public virtual DbSet<Tarea> Tareas { get; set; }
        public virtual DbSet<trabajador_asignado> trabajador_asignado { get; set; }
        public virtual DbSet<Trabajador_empresa> Trabajador_empresa { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
