//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vialisEntities : DbContext
    {
        public vialisEntities()
            : base("name=vialisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acta_reunion> Acta_reunion { get; set; }
        public virtual DbSet<AFP> AFP { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<Detalle_boleta> Detalle_boleta { get; set; }
        public virtual DbSet<Detalle_cotizacion> Detalle_cotizacion { get; set; }
        public virtual DbSet<Detalle_participacion> Detalle_participacion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Etapa> Etapa { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Hito> Hito { get; set; }
        public virtual DbSet<Inspeccion_tecnica> Inspeccion_tecnica { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Participante> Participante { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Registro_avance> Registro_avance { get; set; }
        public virtual DbSet<Seguro_salud> Seguro_salud { get; set; }
        public virtual DbSet<Stock_RRFF_EMPRESA> Stock_RRFF_EMPRESA { get; set; }
        public virtual DbSet<Stock_RRFF_PROYECTO> Stock_RRFF_PROYECTO { get; set; }
        public virtual DbSet<Subcategoria> Subcategoria { get; set; }
        public virtual DbSet<Sueldo> Sueldo { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Trabajador_asignado> Trabajador_asignado { get; set; }
        public virtual DbSet<Trabajador_empresa> Trabajador_empresa { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
