//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_RRFF_PROYECTO
    {
        public string id_material { get; set; }
        public string id_proyecto { get; set; }
        public string marca { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string id_boleta { get; set; }
    
        public virtual Boleta Boleta { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
