//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_RRFF_PROYECTO
    {
        public string id_material { get; set; }
        public string id_proyecto { get; set; }
        public string marca { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string id_boleta { get; set; }
    
        public virtual boleta boleta { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
