//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategoria
    {
        public decimal id_subcategoria { get; set; }
        public string nombre_subcategoria { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
