//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldo
    {
        public decimal id_sueldo { get; set; }
        public Nullable<decimal> id_asignacion { get; set; }
        public Nullable<decimal> dias_trabajados { get; set; }
        public Nullable<decimal> valor_dia { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Trabajador_asignado Trabajador_asignado { get; set; }
    }
}
