//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador_asignado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trabajador_asignado()
        {
            this.Sueldoes = new HashSet<Sueldo>();
        }
    
        public decimal id_asignacion { get; set; }
        public string responsabilidad { get; set; }
        public string id_contrato { get; set; }
        public string id_proyecto { get; set; }
        public string Trabajador_empresa_run { get; set; }
        public Nullable<decimal> Trabajador_empresa_id_trabajador { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sueldo> Sueldoes { get; set; }
        public virtual Trabajador_empresa Trabajador_empresa { get; set; }
    }
}
