//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVialisMVC.Contexto
{
    using System;
    using System.Collections.Generic;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Asistencias = new HashSet<Asistencia>();
            this.Pagoes = new HashSet<Pago>();
        }

        public string run_user { get; set; }
        public string passw { get; set; }
        public string id_contrato { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencias { get; set; }
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagoes { get; set; }
    }

    public class UserBusinessLogic
    {
        string conStr = System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
        public int ValidarUsuario(Usuario usuario)
        {
            using (System.Data.SqlClient.SqlConnection conObj = new System.Data.SqlClient.SqlConnection(conStr))
            {
                System.Data.SqlClient.SqlCommand comObj = new System.Data.SqlClient.SqlCommand("uspLogin", conObj);
                comObj.CommandType = System.Data.CommandType.StoredProcedure;
                comObj.Parameters.Add(new System.Data.SqlClient.SqlParameter("@run_user", usuario.run_user));
                comObj.Parameters.Add(new System.Data.SqlClient.SqlParameter("@passw", usuario.passw));
                conObj.Open();
                return Convert.ToInt32(comObj.ExecuteScalar());
            }
        }
    }
}
